CREATE TABLE `etc_entrust_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` int(11) DEFAULT NULL,
  `card_no` varchar(30) DEFAULT NULL COMMENT '卡号',
  `plate_no` varchar(10) DEFAULT NULL COMMENT '车牌号',
  `in_station_name` varchar(15) DEFAULT NULL COMMENT '入口站名',
  `out_station_name` varchar(15) DEFAULT NULL COMMENT '出口站名',
  `in_op_time` datetime DEFAULT NULL COMMENT '入口时间',
  `out_op_time` datetime DEFAULT NULL COMMENT '出口时间',
  `car_type` int(1) DEFAULT NULL COMMENT '车型(1,大货 2半挂,3,小型)',
  `list_no` varchar(33) DEFAULT '' COMMENT '流水号',
  `batch_no` varchar(15) DEFAULT NULL COMMENT '批次号',
  `list_type` int(1) DEFAULT NULL COMMENT '流水类型(1-正常流水,,2争议支付)',
  `in_lane_no` int(8) DEFAULT NULL COMMENT '入口车道号',
  `out_lane_no` int(8) DEFAULT NULL COMMENT '出口车道号',
  `op_time` datetime DEFAULT NULL COMMENT '收费时间',
  `clear_target_date` datetime DEFAULT NULL COMMENT '清分目标日',
  `before_balance` decimal(15,5) DEFAULT NULL COMMENT '交易前余额(分)',
  `after_balance` decimal(15,5) DEFAULT NULL COMMENT '交易后余额(分)',
  `etc_money` decimal(15,5) DEFAULT NULL COMMENT '实扣金额',
  `statis_date` datetime DEFAULT NULL COMMENT '记账日期',
  `service_fare` decimal(15,5) DEFAULT NULL COMMENT '手续费',
  `is_repayment` int(1) DEFAULT NULL COMMENT '是否还款',
  `created_by` int(9) DEFAULT NULL,
  `updated_by` int(9) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `deleted` int(1) DEFAULT '0',
  `version` smallint(10) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=925 DEFAULT CHARSET=utf8 COMMENT='流水信息';
