CREATE TABLE `safety_check` (
  `SC_ID` int(9) NOT NULL AUTO_INCREMENT,
  `RP_ID` int(9) NOT NULL,
  `CHECK_NAME` varchar(64) COLLATE utf8_bin NOT NULL,
  `CHECK_TIME` datetime NOT NULL,
  `CHECK_DEPT` varchar(64) COLLATE utf8_bin NOT NULL,
  `CHECK_OWNER` varchar(10) COLLATE utf8_bin NOT NULL,
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) NOT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  `PHASE` tinyint(4) DEFAULT NULL COMMENT '1=计划 2=检查 3=整改 4=完成',
  PRIMARY KEY (`SC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=178 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='50_安全检查';



CREATE TABLE `safety_check_item` (
  `SCI_ID` int(9) NOT NULL AUTO_INCREMENT,
  `RP_ID` int(9) NOT NULL,
  `ITEM_NAME` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `CHECK_RESULT` int(11) DEFAULT NULL COMMENT '0=正常 1=异常',
  `CORRECT_ACTION` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `HAS_FINISHED` tinyint(1) DEFAULT NULL,
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) NOT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  `SC_ID` int(9) NOT NULL COMMENT '与SAFETY_CHECK表关联',
  `CHECK_RESULT_CONTENT` varchar(300) COLLATE utf8_bin DEFAULT NULL COMMENT '检查情况详细说明',
  `HAS_FINISHED_CONTENT` varchar(300) COLLATE utf8_bin DEFAULT NULL COMMENT '完成情况详细说明',
  PRIMARY KEY (`SCI_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=315 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='50_检查项目';



CREATE TABLE `safety_inspection` (
  `SAFETY_INSPECTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RP_ID` int(11) NOT NULL,
  `PLAN_ID` int(11) DEFAULT NULL,
  `TEAM_ID` int(11) DEFAULT NULL COMMENT '班组ID',
  `USER_ID` int(11) NOT NULL COMMENT '巡检人',
  `USER_NAME` varchar(60) COLLATE utf8_bin NOT NULL,
  `INSPECTION_DATE` datetime NOT NULL COMMENT '巡检日期',
  `BEGIN_INSPECTION_TIME` datetime NOT NULL COMMENT '开始巡检时间',
  `END_INSPECTION_TIME` datetime DEFAULT NULL COMMENT '结束巡检时间',
  `PLAN_POINT_COUNT` int(11) NOT NULL COMMENT '计划巡检点数',
  `REALITY_POINT_COUNT` int(11) DEFAULT NULL COMMENT '实际巡检点数',
  `BUG_POINT_COUNT` int(11) DEFAULT NULL COMMENT '异常巡检点数',
  `STATUS_CD` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '巡检状态(001巡检中,002巡检结束,003已作废)',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`SAFETY_INSPECTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=186 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_plan` (
  `PLAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RP_ID` int(11) NOT NULL,
  `PLAN_NAME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '排班计划名称',
  `COLOR` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `SETTING_ID` int(11) NOT NULL,
  `FREQUENCY` int(11) DEFAULT NULL COMMENT '每班巡检次数',
  `IS_ALL_POINT` tinyint(4) NOT NULL COMMENT '是否全部巡检点',
  `TEMPLATE_ID` int(11) DEFAULT NULL,
  `IS_TEMPLATE` tinyint(4) NOT NULL COMMENT '是否模版',
  `TIME_LENGTH` decimal(11,2) DEFAULT NULL COMMENT '时段长度',
  `BEGIN_TIME` datetime DEFAULT NULL COMMENT '巡检开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '巡检结束时间',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`PLAN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=618 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_plan_point` (
  `PLAN_POINT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `POINT_ID` int(11) NOT NULL,
  `PLAN_ID` int(11) NOT NULL,
  `RP_ID` int(11) NOT NULL,
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`PLAN_POINT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_plan_team_user` (
  `PLAN_TEAM_USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLAN_ID` int(11) NOT NULL,
  `RP_ID` int(11) NOT NULL COMMENT '园区ID',
  `REF_ID` int(11) NOT NULL COMMENT '班组ID',
  `REF_NAME` varchar(60) COLLATE utf8_bin NOT NULL,
  `TYPE` tinyint(4) NOT NULL COMMENT '1班组，2人员',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`PLAN_TEAM_USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=896 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_point` (
  `POINT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '巡检ID',
  `RP_ID` int(11) NOT NULL,
  `POINT_NAME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '巡检点名称',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`POINT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_record` (
  `RECORD_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '巡检记录ID',
  `SAFETY_INSPECTION_ID` int(11) NOT NULL COMMENT '巡检ID',
  `RP_ID` int(11) NOT NULL COMMENT '园区ID',
  `POINT_XY` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `POINT_ID` int(11) NOT NULL COMMENT '巡检点ID',
  `POINT_NAME` varchar(60) COLLATE utf8_bin NOT NULL COMMENT '巡检点名称',
  `INSPECTION_TIME` datetime NOT NULL,
  `IS_BUG` tinyint(4) NOT NULL COMMENT '是否异常',
  `REMARK` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`RECORD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=448 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_setting` (
  `SETTING_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '巡检配置ID',
  `RP_ID` int(11) NOT NULL COMMENT '园区ID',
  `TIME_FRAME_LENGTH` double(11,0) DEFAULT NULL COMMENT '时段长度',
  `TIME_FRAME_NAME` varchar(60) COLLATE utf8_bin NOT NULL COMMENT '时段名称',
  `IS_ACROSS_DAY` tinyint(4) DEFAULT NULL,
  `BEGIN_TIME` datetime NOT NULL COMMENT '开始时间',
  `END_TIME` datetime NOT NULL COMMENT '结束时间',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`SETTING_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=148 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_inspection_track` (
  `TRACK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SAFETY_INSPECTION_ID` int(11) DEFAULT NULL,
  `CONTENT` text COLLATE utf8_bin,
  PRIMARY KEY (`TRACK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_team` (
  `TEAM_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '班组ID',
  `RP_ID` int(11) DEFAULT NULL COMMENT '园区ID',
  `TEAM_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '班组名称',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`TEAM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



CREATE TABLE `safety_user_team` (
  `USER_TEAM_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户班组ID',
  `RP_ID` int(11) DEFAULT NULL COMMENT '园区ID',
  `TEAM_ID` int(11) DEFAULT NULL COMMENT '班组ID',
  `USER_ID` int(11) DEFAULT NULL COMMENT 'DELETED	int	9	0	0	0	0	0	0	0	0	未删除为0				0	0',
  `DELETED` int(9) NOT NULL DEFAULT '0' COMMENT '未删除为0',
  `CREATED_BY` int(9) NOT NULL COMMENT '创建人的操作员ID',
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_BY` int(9) DEFAULT NULL COMMENT '更新人的操作员ID',
  `UPDATED_TIME` datetime DEFAULT NULL,
  `VERSION` int(11) NOT NULL DEFAULT '1' COMMENT '记录版本号,编辑后进行修改,可用于乐观锁',
  PRIMARY KEY (`USER_TEAM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;